version: "3.8"
services:
  back-end:
    build: ./back-end
    volumes:
      - ./backend:/visual-programming/back-end
    ports:
      - "8000:8000"
    env_file: ./backend/.env
    stdin_open: true
    tty: true
    command: cd vp && pipenv run python manage.py runserver 0.0.0.0:8000
  front-end:
    build: ./front-end
    volumes:
      - ./front-end:/visual-programming/front-end
      # One-way volume to use node_modules from inside image
      - /visual-programming/front-end/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - back-end
    command: npm start
