# This workflow tests front-end

name: Test front-end

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  test-front-end:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository, for access in the workflow
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        cd front-end
        npm ci

    - name: Run unit tests
      run: |
        cd front-end
        npm test
